### ISSUE TITLE
sdist for 0.5.0 is not available on PyPI

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [dbt-labs/dbt-extractor#71]
Hello, I noticed that the sdist for 0.5.0 was not published on PyPI. There is additionally no tag in the repository, so it's difficult to know which commit was used to generate the 0.5.0 binaries found on PyPI.

Would it be possible to either publish an sdist, or add a tag or both so that the source used to generate the wheels can more easily be traced back?

Thanks!

**Comment by maresb** [comment]
Same story on conda-forge; thanks @JeanChristopheMorinPerso for taking the initiative on this! It has been holding up several of the releases.

https://github.com/conda-forge/dbt-extractor-feedstock/issues/12

**Comment by peterallenwebb** [comment]
Thanks for bringing this to our attention. We're planning to release an update with the source distribution early next week, after the long holiday weekend in the US.

**Comment by peterallenwebb** [comment]
@maresb @JeanChristopheMorinPerso dbt-extractor 0.5.1 has been released, now with an sdist. Let us know if you have any further issues, and thanks again!

**Comment by maresb** [comment]
Thanks @peterallenwebb! It looks like we're back in business. I'll look into shepherding the backlog through within the next few days.

**Comment by maresb** [comment]
Everything seemed to go smoothly over on conda-forge; I think we're now all up-to-date.

CC @nevdelap
